- name:  app_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name:  java_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: java_setup.yaml

- name : install python libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
     - cryptography
     - PyMySQL


- name: connect to mysql
  community.mysql.mysql_db:
    state: import
    name: all
    login_user: root
    login_password: RoboShop@1
    login_host: "{{ MYSQL_HOST }}"
    target: "{{ item }}"
  loop:
      - /app/db/schema.sql
      - /app/db/app-user.sql 
      - /app/db/master-data.sql

- name: import_role and do service setup
  ansible.builtin.import_role:
    name: common
    tasks_from: services_setup