  - name:  app_setup
    ansible.builtin.import_role:
      name: common
      tasks_from: app_setup.yaml

  - name:  python_setup
    ansible.builtin.import_role:
      name: common
      tasks_from: python_setup.yaml


  - name: import_role and do service setup
    ansible.builtin.import_role:
      name: common
      tasks_from: services_setup