- name: copy rabbitmq repo
  ansible.builtin.copy: 
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
- name: install rabbitmq
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

- name: start services
  ansible.builtin.service:
    name: rabbitmq-server
    enabled: yes 
    state: started
- name: set permissions to use
  community.rabbitmq.rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_password }}"
    permissions:
      - vhost: /
        configure_priv : .*
        read_priv: .*
        write_priv: .*
    state: present 
  