  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: create Roboshop System user
      system: true
      shell: /sbin/nologin
      home: /app


  - name: remove app directory if already exists
    ansible.builtin.file: 
      path: /app
      state: absent

  - name: create app directory 
    ansible.builtin.file:
      state: directory 
      path: /app


  - name: download code from url
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
      dest: /tmp/{{ component }}.zip

  - name: unzip the code in app directory
    ansible.builtin.unarchive:
      src: /tmp/{{ component }}.zip
      dest: /app
      remote_src: yes
      
  - name: Change ownership of /app
    ansible.builtin.file:
      path: /app
      owner: roboshop
      group: roboshop
      recurse: yes

